import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';


const sidebars: SidebarsConfig = {
    docsSidebar: [
        {
            type: 'doc',
            id: 'index',
            label: 'Index',
        },
        {
            type: 'category',
            label: 'Test & Publish',
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'test-and-publish',
                }
            ],
        },
    ]
};

export default sidebars;
