import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';


const sidebars: SidebarsConfig = {
    docsSidebar: [
        {
            type: 'doc',
            id: 'index',
            label: 'Welcome',
        },
        {
            type: 'category',
            label: 'Getting Started',
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'get-started'
                }
            ],
        },
        {
            type: 'category',
            label: 'Workspace',
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'workspace'
                }
            ],
        },
        {
            type: 'category',
            label: 'Test & Publish',
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'test-and-publish',
                }
            ],
        },
        {
            type: 'category',
            label: 'Integrations',
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'integrations',
                }
            ],
        },
        {
            type: 'category',
            label: 'Debugging',
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'debugging',
                }
            ],
        },
        {
            type: 'category',
            label: 'Concepts',
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'concepts',
                }
            ],
        },
    ]

};

export default sidebars;
