import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';


const sidebars: SidebarsConfig = {
    docsSidebar: [
        {
            type: 'doc',
            id: 'index',
            label: 'Getting Started',
        },
        {
            type: 'category',
            label: 'Workspace',
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'workspace'
                }
            ],
        }
    ]

};

export default sidebars;
